/*
 * Copyright 2000-2023 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package bazel.bazel.events

// Payload on events reporting about individual test action.

data class TestResult(
        override val id: Id,
        override val children: List<Id>,
        val label: String,
        val run: Int,
        val shard: Int,
        val attempt: Int,
        // The status of this test.
        val status: TestStatus,
        // Additional details about the status of the test. This is intended for
        // user display and must not be parsed.
        val statusDetails: String,
        val cachedLocally: Boolean,
        // Time in milliseconds since the epoch at which the test attempt was started.
        // Note: for cached test results, this is time can be before the start of the
        // build.
        val testAttemptStartMillisEpoch: Long,
        // Time the test took to run. For locally cached results, this is the time
        // the cached invocation took when it was invoked.
        val testAttemptDurationMillis: Long,
        // Files (logs, test.xml, undeclared outputs, etc) generated by that test
        // action.
        val testActionOutput: List<File>,
        // Warnings generated by that test action.
        val warning: List<String>) : BazelContent